### PR TITLE
[SEDONA-636] Parser extension optimization

### PR DESCRIPTION
**Pull request by freamdx**
* optimize parser extension

### CODE REVIEW

**Comment by jiayuasu** [comment]
@freamdx Can you explain the purpose of this PR?

**Comment by freamdx** [comment]
> @freamdx Can you explain the purpose of this PR?

we will integrate sedona into iceberg/paimon + gluten.

**Comment by jiayuasu** [comment]
@freamdx Can you update the description of this PR and explain the purpose of this PR (i.e., why do you make these changes)?

**Comment by Kontinuation** [comment]
Will the parser fallback to delegated parser when parsing fails? We had https://github.com/apache/sedona/pull/1547 to enable this fallback, otherwise the parser extensions of Iceberg or Delta won't work correctly if they are registered prior to the initialization of Sedona.

**Comment by freamdx** [comment]
sedona parser override parsePlan() == Huà shé tiān zú

**Comment by freamdx** [comment]
> > > Will the parser fallback to delegated parser when parsing fails? We had #1547 to enable this fallback, otherwise the parser extensions of Iceberg or Delta won't work correctly if they are registered prior to the initialization of Sedona.
> > 
> > 
> > 
> > 1. iceberg needs to be modified to support geometry type，integrate sedona is the best solution
> > 2. the parser of iceberg code, like this:
> >    class IcebergSparkSqlExtensionsParser(delegate: ParserInterface) extends ParserInterface ... {
> >    ......
> >    // if use SedonaSqlParser, then delegate is SedonaSqlParser
> >    override def parseDataType(sqlText: String): DataType = {
> >    delegate.parseDataType(sqlText)
> >    }
> > 
> > ...... // override def parsePlan() in SedonaSqlParser is useless override def parsePlan(sqlText: String): LogicalPlan = { val sqlTextAfterSubstitution = substitutor.substitute(sqlText) if (isIcebergCommand(sqlTextAfterSubstitution)) { parse(sqlTextAfterSubstitution) { parser => astBuilder.visit(parser.singleStatement()) }.asInstanceOf[LogicalPlan] } else { ...... } } ...... }
> 
> If the iceberg extension is initialized after the initialization of Sedona, `IcebergSparkSqlExtensionsParser` will certainly work correctly, since `delegate` of `IcebergSparkSqlExtensionsParser` will be SedonaSqlParser. What if Sedona got initialized after iceberg's Spark SQL extension, will SQL parsing be delegated to `IcebergSparkSqlExtensionsParser` in this case?
> 
> If initializing Sedona defeats any previously registered SQL parser, and it is the desired behavior, we'd better document it somewhere to inform the user.

-----------------
look sedona's ParserRegistrator register(): {
      val parser = ParserFactory.getParser(parserClassName, delegate)
      val field = sparkSession.sessionState.getClass.getDeclaredField("sqlParser")
      field.setAccessible(true)
      field.set(sparkSession.sessionState, parser)
}
so, SessionState Field("sqlParser") is always SedonaSqlParser, it doesn't matter the inject order

**Comment by freamdx** [comment]
> sedona parser override parsePlan() == Huà shé tiān zú

SedonaSqlParser extends SparkSqlParser, SparkSqlParser is default SqlParser, original implementation is perfect

**Comment by Kontinuation** [comment]
> so, SessionState Field("sqlParser") is always SedonaSqlParser, it doesn't matter the inject order

From what I observed, `sparkSession.sessionState.sqlParser` will be `IcebergSparkSqlExtensionsParser` right after iceberg extension is applied. If Sedona is initialized afterwards, it will replace `sparkSession.sessionState.sqlParser` with `SedonaSqlParser`. The delegation hierarchy will be something like this:

```
SedonaSqlParser
  └─ IcebergSparkSqlExtensionsParser
       └─ <delegated parser instance>
```

If `SedonaSqlParser` cannot fallback to the delegated parser, the special SQL syntaxes such as `CALL ...` defined by iceberg won't work. Here is an example using iceberg 1.7.0 and a locally built Sedona with this patch applied:

```
pyspark --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.7.0 \
        --jars "$SEDONA_SHADED_JAR" \
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
        --conf spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog \
        --conf spark.sql.catalog.local.type=hadoop \
        --conf spark.sql.catalog.local.warehouse=$HOME/local/iceberg/warehouse

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.5.1
      /_/

Using Python version 3.11.6 (main, Oct  2 2023 20:46:14)
Spark context Web UI available at http://192.168.200.155:4040
Spark context available as 'sc' (master = local[*], app id = local-1732620541890).
SparkSession available as 'spark'.
>>> from sedona.spark import *
>>> sedona = SedonaContext.create(spark)
24/11/26 19:33:39 WARN RasterRegistrator$: Geotools was not found on the classpath. Raster operations will not be available.
>>> spark.sql("CALL local.system.remove_orphan_files (table => 'test_db.test_table', dry_run => true)").show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/local/spark/spark-3.5.1-bin-hadoop3/python/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/local/spark/spark-3.5.1-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/workspace/local/spark/spark-3.5.1-bin-hadoop3/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'CALL'.(line 1, pos 0)

== SQL ==
CALL local.system.remove_orphan_files (table => 'test_db.test_table', dry_run => true)
^^^

>>> 
```

Even if we add `SedonaSqlExtensions` to `spark.sql.extensions` and get rid of manual initialization, there's still problem with SQL parsing:

```
pyspark --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.7.0 \
        --jars "$SEDONA_SHADED_JAR" \
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.apache.sedona.sql.SedonaSqlExtensions \
        --conf spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog \
        --conf spark.sql.catalog.local.type=hadoop \
        --conf spark.sql.catalog.local.warehouse=$HOME/local/iceberg/warehouse

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.5.1
      /_/

Using Python version 3.11.6 (main, Oct  2 2023 20:46:14)
Spark context Web UI available at http://192.168.200.155:4040
Spark context available as 'sc' (master = local[*], app id = local-1732621080857).
SparkSession available as 'spark'.
>>> spark.sql("CALL local.system.remove_orphan_files (table => 'test_db.test_table', dry_run => true)").show()
24/11/26 19:38:14 WARN RasterRegistrator$: Geotools was not found on the classpath. Raster operations will not be available.
+--------------------+
|orphan_file_location|
+--------------------+
+--------------------+

>>> spark.sql("CALL local.system.remove_orphan_files (table => 'test_db.test_table', dry_run => true)").show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/local/spark/spark-3.5.1-bin-hadoop3/python/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/local/spark/spark-3.5.1-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/workspace/local/spark/spark-3.5.1-bin-hadoop3/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near 'CALL'.(line 1, pos 0)

== SQL ==
CALL local.system.remove_orphan_files (table => 'test_db.test_table', dry_run => true)
^^^

>>> 
```

I like the idea of overriding `astBuilder`, as it enables better integration with iceberg. However I'm a bit worried about removing the fallback path, since it may break iceberg's sql parsing when sedona and iceberg coexists.

**Comment by freamdx** [comment]
@jiayuasu @Kontinuation 
code review again, thks.

**Pull request closed without merging**
