### PR TITLE
[SEDONA-348] Implement ST_MakePoint

### PR DESCRIPTION
**Pull request by yyy1000**
## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket will be https://issues.apache.org/jira/browse/SEDONA-348. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?
Add ST_MakePoint to [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.

## How was this patch tested?
1. Comprehensive unit tests in [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common)
2. Integration unit tests in [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and python.

## Did this PR include necessary documentation updates?
- Yes, I have updated the documentation update.

### CODE REVIEW

**Comment by jiayuasu** [comment]
@yyy1000 Please fix this PR using the solution provided by https://github.com/apache/sedona/pull/952

**Comment by yyy1000** [comment]
> @yyy1000 Please fix this PR using the solution provided by #952

Got it. Fixed it already.

**Review by jiayuasu — CHANGES_REQUESTED** [review]
Please also add documentation.

**Comment by jiayuasu** [comment]
@yyy1000 Are you planning to implement ST_MakePointM?

**Review by jiayuasu — APPROVED** [review]

**Comment by yyy1000** [comment]
> @yyy1000 Are you planning to implement ST_MakePointM?

I can implement it next week. :)

**Pull request merged**
