### PR TITLE
[SEDONA-473] Remove ucar from spark-shaded pom

### PR DESCRIPTION
**Pull request by iGN5117**
## Did you read the Contributor Guide?
- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-473. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?
- Remove ucar from spark-shaded pom

## How was this patch tested?
- Passed existing tests

## Did this PR include necessary documentation updates?
- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

**Comment by Kontinuation** [comment]
This does not resolve [SEDONA-473](https://issues.apache.org/jira/browse/SEDONA-473), since `cdm-core` is introduced by the parent POM, not the shaded POM. Actually the POM published to maven central for spark-shaded is a dependency-reduced POM, which does not have dependencies in `compile` scope (See https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.5_2.12/1.5.1/sedona-spark-shaded-3.5_2.12-1.5.1.pom).

The correct way to resolve this issue is to remove https://github.com/apache/sedona/blob/master/pom.xml#L132-L135 in the parent POM.

**Review by Kontinuation — COMMENTED** [review]
This does not resolve [SEDONA-473](https://issues.apache.org/jira/browse/SEDONA-473), since `cdm-core` is introduced by the parent POM, not the shaded POM. Actually the POM published to maven central for spark-shaded is a dependency-reduced POM, which does not have dependencies in `compile` scope (See https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.5_2.12/1.5.1/sedona-spark-shaded-3.5_2.12-1.5.1.pom).

The correct way to resolve this issue is to remove https://github.com/apache/sedona/blob/master/pom.xml#L132-L135 in the parent POM.

**Comment by iGN5117** [comment]
> This does not resolve [SEDONA-473](https://issues.apache.org/jira/browse/SEDONA-473), since `cdm-core` is introduced by the parent POM, not the shaded POM. Actually the POM published to maven central for spark-shaded is a dependency-reduced POM, which does not have dependencies in `compile` scope (See https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.5_2.12/1.5.1/sedona-spark-shaded-3.5_2.12-1.5.1.pom).
> 
> The correct way to resolve this issue is to remove https://github.com/apache/sedona/blob/master/pom.xml#L132-L135 in the parent POM.

@Kontinuation thanks for checking this PR. I was confused if I would need to keep ucar in the parent pom to support NetCDF functionality, but even removing it makes no difference. 
I've reverted my earlier commit and removed ucar from sedona/pom.xml now. Please approve if it looks good!

**Comment by Kontinuation** [comment]
> @Kontinuation thanks for checking this PR. I was confused if I would need to keep ucar in the parent pom to support NetCDF functionality, but even removing it makes no difference. I've reverted my earlier commit and removed ucar from sedona/pom.xml now. Please approve if it looks good!

Now it should be good, but I prefer removing the unused dependency instead of commenting it out.

**Comment by iGN5117** [comment]
> > @Kontinuation thanks for checking this PR. I was confused if I would need to keep ucar in the parent pom to support NetCDF functionality, but even removing it makes no difference. I've reverted my earlier commit and removed ucar from sedona/pom.xml now. Please approve if it looks good!
> 
> Now it should be good, but I prefer removing the unused dependency instead of commenting it out.

Yes ofcourse, the comment was temporary. Removed it completely.

**Review by Kontinuation — APPROVED** [review]

**Pull request merged**
