### PR TITLE
[SEDONA-249] Add jvm flags for running tests on Java 17

### PR DESCRIPTION
**Pull request by umartin**
## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-249. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

Add jvm flags to test plugins to make it possible to run tests on Java 17. This will make life easier for contributors running Java 17 locally.

This PR does not add Java 17 to the test matrix for github actions.
This PR does not make the tests pass on Java 17. Currently CRSTransformationTest.testPolygonDistanceJoinWithCRSTransformation in sedona-core fails on Java 17.

## How was this patch tested?

All tests pass on Java 8.

## Did this PR include necessary documentation updates?

- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

**Comment by jiayuasu** [comment]
@umartin Thanks for bringing this up. Interestingly, I found CRSTransformationTest.testPolygonDistanceJoinWithCRSTransformation also failed on Java 11. I haven't figured why. Any idea?

**Comment by umartin** [comment]
I think there was a patch in a point release of Java 11 that changed the string representation of floats. For me it fails on Java 11.0.17 although I remember it passing on earlier version of Java 11. It the test reads geometries from csv files they could be interpreted differently depending on java version.

I remember tweaking some tests in sedona-sql when that change hit me. https://github.com/apache/sedona/blob/master/sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala#L163

The test runs a distance join in RDD with polygons. The Circle geometry is only valid for points. Maybe the test can be removed?

**Comment by jiayuasu** [comment]
@umartin Yes! Can you remove that flaky test?

**Comment by umartin** [comment]
@jiayuasu No problem! I added a commit removing the test.

**Review by jiayuasu — APPROVED** [review]

**Pull request merged**
