### PR TITLE
[SEDONA-285] Added docker images for spark-sedona-zeppelin and spark-sedona-jupyterlab

### PR DESCRIPTION
**Pull request by kartikeyhadiya**
Added docker images for spark-sedona:1.3.1-zeppelin and spark-sedona1.4.0-jupyterlab

Issue: #842

## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, [SEDONA-285](https://issues.apache.org/jira/browse/SEDONA-285)

## What changes were proposed in this PR?
Added docker images for spark-sedona:1.3.1-zeppelin and spark-sedona1.4.0-jupyterlab

## How was this patch tested?

Local environment with docker.

## Did this PR include necessary documentation updates?

- Yes, I have added readmes in respective folders.

### CODE REVIEW

**Comment by jiayuasu** [comment]
@kartikeyhadiya Thanks for your contribution. A few comments:

1. Since this is a major contribution, please create a JIRA ticket first.
2. Please do not duplicate any data files in the source repo. The source repo already has a couple of data files in `binder`. Please try to reuse those via Dockerfile.
3. Please do not directly copy jars to the source repo. Please download jars on the fly via Dockerfile.
4. All source code such as .sh script must have Apache License as the file header.
5. Once everything is done, you will need to add the docker compilation to GitHub Action with a Yaml file.

**Comment by kartikeyhadiya** [comment]
Thanks for your input. 
For 2 & 3 point i just thought that if anyone wants to replicate they can just download the docker folder and start working but, I will make the necessary changes. 
Can you please elaborate on 5 point? I have never used github actions, are you referring something like this https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action or https://josephrodriguezg.medium.com/build-and-publish-docker-images-with-github-actions-78be3b3fbb9b ?

**Comment by kartikeyhadiya** [comment]
I have created jira ticket and included it in main comment

**Comment by jiayuasu** [comment]
@kartikeyhadiya Yes, for No.5, we will need [docs.github.com/en/actions/creating-actions/creating-a-docker-container-action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)

**Comment by kartikeyhadiya** [comment]
Hey, @jiayuasu sorry for so much delay had a busy month at work. 
- I have made all the changes you proposed, please can you have a look. I didn't make github action for zeppelin docker file as I think if zeppelin is not updated sooner or later it will be of no use, still I have kept a dockerfile for that. 
- For publishing to dockerhub, please create 2 secrets named "DOCKERHUB_USERNAME" and "DOCKERHUB_PASSWORD". For now I have kept my repository as a placeholder, please let me know the repository to which I need to publish so I can make that changes.

**Comment by kartikeyhadiya** [comment]
Hey, @jiayuasu just following up on this.

**Comment by jiayuasu** [comment]
@kartikeyhadiya Thanks for the great work here. I will take a look your fork and try to run it myself.

**Comment by kartikeyhadiya** [comment]
Thank you, please let me know if anything else is required.

**Comment by jiayuasu** [comment]
@kartikeyhadiya Due to the complexity of this task, I have taken over this and created another PR based on this PR: https://github.com/apache/sedona/pull/939 Thanks for your help!

**Pull request closed without merging**
