### PR TITLE
[SEDONA-242] R: Update dependencies + fix failing test

### PR DESCRIPTION
**Pull request by gregleleu**
## What changes were proposed in this PR?
Updating dependencies in R package

## How was this patch tested?
Ran R tests

## Did this PR include necessary documentation updates?
- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

**Comment by gregleleu** [comment]
The R build has failed: it's not the old error -> all the tests failed because Spark did not start.
I am unable to reproduce on my computer

**Comment by jiayuasu** [comment]
@gregleleu I also don't know what happened...

**Comment by jiayuasu** [comment]
@gregleleu It is weird that the exact CI passed on my fork: https://github.com/jiayuasu/sedona/pull/1

**Comment by gregleleu** [comment]
@jiayuasu The logs were showing an issue with the jts core jars (between version 1.18.0 and 1.18.1) maybe it's an issue with resolving dependencies and/or cached versions?

Also, should I bump the dependencies to the 1.4.0 versions? Eg 1.19.0 for jts core

**Comment by jiayuasu** [comment]
@gregleleu Yes, please bump the dependencies version to the 1.4.0 version. Thanks for reminding me about the cache issue. The CI passed after I cleaned up the cache!

**Review by jiayuasu — APPROVED** [review]

**Pull request merged**
